name: Festival2
author: Genboy
version: 2.0-dev
main: genboy\Festival2\Main
load: POSTWORLD
api: [3.0.0,4.0.0]
website: "https://github.com/genboy/Festival2"
commands:
  fe:
    description: "Allows you to manage Festival area's and events."
    usage: "See info: /fe (in development)"
    permission: festival.command.fe
permissions:
  festival:
    description: "Allows access to all Festival features."
    default: false
    children:
      festival.access:
        description: "Allows access to editing festival areas and events."
        default: op
      festival.command:
        description: "Allows access to all Festival commands."
        default: false
        children:
          festival.command.fe:
            description: "Allows access to the Festival area command."
            default: op
            children:
              festival.command.fe.pos1:
                description: "Allows access to the Festival pos1 subcommand."
                default: op
              festival.command.fe.pos2:
                description: "Allows access to the Festival pos2 subcommand."
                default: op
              festival.command.fe.create:
                description: "Allows access to the Festival create subcommand."
                default: op
              festival.command.fe.list:
                description: "Allows access to the Festival list subcommand."
                default: op
              festival.command.fe.here:
                description: "Allows access to the Festival here subcommand."
                default: op
              festival.command.fe.tp:
                description: "Allows access to the Festival tp subcommand."
                default: op
              festival.command.fe.desc:
                description: "Allows access to the Festival description subcommand."
                default: op
              festival.command.fe.flag:
                description: "Allows access to the Festival flag subcommand."
                default: op
              festival.command.fe.delete:
                description: "Allows access to the Festival delete subcommand."
                default: op
              festival.command.fe.whitelist:
                description: "Allows access to the Festival whitelist subcommand."
                default: op
              festival.command.fe.command:
                description: "Allows access to the Festival command subcommand."
                default: op
