name: Festival2
author: Genboy
version: 2.0-dev
main: genboy\Festival2\Festival
load: POSTWORLD
api: [3.0.0,4.0.0]
website: "https://github.com/genboy/Festival2"
commands:
  fc:
    description: "Allows you to manage Festival2 area's and events."
    usage: "See info: /fc (festival2 command in development)"
    permission: festival2.command.fc
permissions:
  festival2:
    description: "Allows access to all Festival Board features."
    default: false
    children:
      festival2.access:
        description: "Allows access to use genloci."
        default: op
      festival2.command:
        description: "Allows access to all genloci commands."
        default: false
        children:
          festival2.command.fc:
            description: "Allows access to the genloci board commands."
            default: op
